import type { DomainEngineeringPolicy } from "@harness/core/domain-engineering-hook";

export const policy: DomainEngineeringPolicy = {
 plugin:"php-engineering",
 displayName:"PHP Engineering",
 protections:[
 { id:"composer-lock", match:/(?:^|\/)composer\.lock$/iu, reason:"composer.lock is generated by Composer.", recovery:"Change composer.json and regenerate the lock with Composer." },
 { id:"composer-vendor", match:/(?:^|\/)vendor(?:\/|$)/iu, reason:"vendor is owned by Composer.", recovery:"Change project sources or declarations and reinstall dependencies." },
],
 validators:[
 { id:"phpSyntax", enforcement:"deterministic", kind:"php", match:/\.php$/iu, mode:"block" },
 { id:"composerValidate", enforcement:"deterministic", kind:"composer", match:/(?:^|\/)composer\.json$/iu, mode:"block" },
],
};
