import type { DomainEngineeringPolicy } from "@harness/core/domain-engineering-hook";

export const policy: DomainEngineeringPolicy = {
 plugin:"rust-engineering",
 displayName:"Rust Engineering",
 protections:[
 { id:"cargo-lock", match:/(?:^|\/)Cargo\.lock$/iu, reason:"Cargo.lock is generated by Cargo.", recovery:"Change Cargo.toml and regenerate the lock with Cargo." },
],
 validators:[
 { id:"rustfmt", kind:"rustfmt", match:/\.rs$/iu, mode:"report" },
],
};
