import type { DomainEngineeringPolicy } from "@harness/core/domain-engineering-hook";

export const policy: DomainEngineeringPolicy = {
 plugin:"go-engineering",
 displayName:"Go Engineering",
 protections:[
 { id:"go-module-checksums", match:/(?:^|\/)go\.sum$/iu, reason:"go.sum is generated by the Go module toolchain.", recovery:"Change go.mod or imports and regenerate checksums with Go module commands." },
],
 validators:[
 { id:"gofmt", enforcement:"advisory", kind:"gofmt", match:/\.go$/iu, mode:"report" },
],
};
