import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import { cwd, sessionId } from "./hook-io.mjs";

export function finalText(event) { return [event?.last_assistant_message, event?.lastAssistantMessage, event?.assistant_response, event?.assistantResponse, event?.final_output, event?.finalOutput, event?.response, event?.message?.content].find((value) => typeof value === "string") ?? ""; }
export function completionStatus(text) { if (/(?:⚠️\s*DONE_WITH_CONCERNS|(?:退出状态|状态)[:：]\s*(?:⚠️\s*)?DONE_WITH_CONCERNS|(?:^|\n)\s*DONE_WITH_CONCERNS\s*(?:\n|$))/u.test(text)) return "done-with-concerns"; if (/(?:🚫\s*BLOCKED|(?:退出状态|状态)[:：]\s*(?:🚫\s*)?BLOCKED|(?:^|\n)\s*BLOCKED\s*(?:\n|$))/u.test(text)) return "blocked"; if (/(?:❓\s*NEEDS_CONTEXT|(?:退出状态|状态)[:：]\s*(?:❓\s*)?NEEDS_CONTEXT|(?:^|\n)\s*NEEDS_CONTEXT\s*(?:\n|$))/u.test(text)) return "needs-context"; if (/(?:✅\s*DONE|(?:退出状态|状态)[:：]\s*(?:✅\s*)?DONE|(?:^|\n)\s*DONE\s*(?:\n|$))/u.test(text)) return "done"; return null; }
export function successful(text) { return ["done", "done-with-concerns"].includes(completionStatus(text)); }
export function activeSkills(event) { const values = [event?.activeSkillIds, event?.active_skill_ids, event?.skills, event?.context?.activeSkillIds, process.env.AI_EXPERTS_ACTIVE_SKILLS?.split(",")].flat().filter((value) => typeof value === "string"); return new Set(values.map((value) => value.split("/").at(-1))); }
function readJson(path) { try { return JSON.parse(readFileSync(path, "utf8")); } catch { return null; } }
export function receipts(event) { const records = [], runs = join(cwd(event), ".process-confidence", "runs"); if (existsSync(runs)) { for (const runId of readdirSync(runs)) { const dir = join(runs, runId, "receipts"); if (!existsSync(dir)) continue; for (const name of readdirSync(dir)) if (name.endsWith(".json")) { const value = readJson(join(dir, name)); if (value) records.push(value); } } } const embedded = [event?.receipts, event?.telemetry, event?.audit_entries, event?.auditEntries].flat().filter((value) => value && typeof value === "object"); records.push(...embedded); const current = sessionId(event); return records.filter((item) => !current || !item.sessionId && !item.session_id || item.sessionId === current || item.session_id === current); }
function field(record, ...names) { for (const name of names) if (record?.[name] !== undefined) return record[name]; return undefined; }
export function receiptTool(record) { return field(record, "toolId", "tool_id", "mcpToolId", "mcpTool_id"); }
export function receiptInvocation(record) { return field(record, "invocationId", "invocation_id"); }
export function receiptPassed(record) { return field(record, "outcome") === "pass" || Number(field(record, "exitCode", "exit_code")) === 0 && field(record, "timedOut", "timed_out") !== true; }
export function tagMap(text) { const tags = new Map(); for (const match of text.matchAll(/\[MCP实测:([a-z0-9]+(?:-[a-z0-9]+)*)@([A-Za-z0-9._:-]+)\]/gu)) { const ids = tags.get(match[1]) ?? new Set(); ids.add(match[2]); tags.set(match[1], ids); } return tags; }
function timestamp(record) { const value = field(record, "ts", "at", "observedAt"); if (typeof value === "number") return value; const parsed = Date.parse(String(value ?? "")); return Number.isFinite(parsed) ? parsed : 0; }
export function missingTools(event, text, required, options = {}) { const tags = tagMap(text), all = receipts(event), latestMutation = options.freshAfterMutation ? all.filter((item) => field(item, "telemetry_event_type", "telemetryEventType") === "workspace_mutation").reduce((latest, item) => Math.max(latest, timestamp(item)), 0) : 0, valid = new Set(all.filter((item) => receiptPassed(item) && (!options.evidenceKind || field(item, "evidenceKind", "evidence_kind") === options.evidenceKind) && (!options.effectScope || field(item, "effectScope", "effect_scope") === options.effectScope) && timestamp(item) >= latestMutation).flatMap((item) => { const tool = receiptTool(item), invocation = receiptInvocation(item); return tool && invocation ? [`${tool}@${invocation}`] : []; })); return required.filter((tool) => ![...(tags.get(tool) ?? [])].some((id) => valid.has(`${tool}@${id}`))); }
export function recovery(missing, action) { return [`missing: ${missing}`, `autoAction: ${action}`, "userDecision: 只有需要用户凭据、授权、不可逆操作或业务裁决时才交还用户。", "retry: 补齐可验证证据后保留原结论并重新提交完成态。"].join("\n"); }
