import type { DomainEngineeringPolicy } from "@harness/core/domain-engineering-hook";

export const policy: DomainEngineeringPolicy = {
 plugin:"ios-engineering",
 displayName:"iOS Engineering",
 protections:[
 { id:"ios-lockfiles", match:/(?:^|\/)(?:Package\.resolved|Podfile\.lock)$/iu, reason:"Apple dependency lockfiles are generated by SwiftPM or CocoaPods.", recovery:"Change Package.swift or Podfile and regenerate with the dependency manager." },
 { id:"ios-dependency-directories", match:/(?:^|\/)(?:Pods|Carthage\/Build|\.build\/checkouts)(?:\/|$)/iu, reason:"The target is inside an iOS dependency directory.", recovery:"Change declarations or sources, then reinstall dependencies." },
],
 validators:[
 { id:"swiftParse", kind:"swift", match:/\.swift$/iu, mode:"block" },
 { id:"plistLint", kind:"plist", match:/\.plist$/iu, mode:"block" },
],
};
