import { repoContainsPath, type DomainEngineeringPolicy, type DomainSourceScanHit } from "@harness/core/domain-engineering-hook";
import { detectComposeSource } from "./lib/compose-detect.js";

const KOTLIN_SOURCE = /\.(?:kt|kts)$/iu;

function composeHits(codes: ReadonlySet<string>): (filePath: string, source: string) => DomainSourceScanHit[] {
  return (_filePath, source) => detectComposeSource(source)
    .filter((hit) => codes.has(hit.code))
    .map((hit) => ({ line: hit.line, code: hit.code, message: hit.message }));
}

export const policy: DomainEngineeringPolicy = {
 plugin:"android-engineering",
 displayName:"Android Engineering",
 active:(context)=>/(?:AndroidManifest\.xml|res\/.+\.xml)$/iu.test(context.relativePath)||repoContainsPath(context.root,/(?:^|\/)AndroidManifest\.xml$/iu),
 protections:[
 { id:"android-gradle-locks", match:/(?:^|\/)gradle\.lockfile$|(?:^|\/)gradle\/dependency-locks\/[^/]+\.lockfile$/iu, reason:"Android dependency locks are generated by Gradle.", recovery:"Change Gradle dependency declarations and regenerate locks through the project wrapper." },
 { id:"android-gradle-cache", match:/(?:^|\/)\.gradle(?:\/|$)/iu, reason:"The Android Gradle cache is tool-owned.", recovery:"Change sources or declarations and let Gradle recreate the cache." },
],
 validators:[
 { id:"androidXml", kind:"xml", match:/(?:AndroidManifest\.xml|res\/.+\.xml)$/iu, mode:"block" },
 { id:"androidJson", kind:"json", match:/(?:^|\/)google-services\.json$/iu, mode:"block" },
],
 sourceScans:[
 { id:"composeCollectAsState", match:KOTLIN_SOURCE, mode:"report", inspect:composeHits(new Set(["COLLECT_AS_STATE","PAGING_COLLECT_AS_STATE"])) },
 { id:"composePrimitiveState", match:KOTLIN_SOURCE, mode:"report", inspect:composeHits(new Set(["PRIMITIVE_MUTABLE_STATE"])) },
 { id:"composeLiteralColor", match:KOTLIN_SOURCE, mode:"report", inspect:composeHits(new Set(["HARDCODED_ON_THEME"])) },
 ],
};
