import type { DomainEngineeringPolicy } from "@harness/core/domain-engineering-hook";

export const policy: DomainEngineeringPolicy = {
 plugin:"nix-engineering",
 displayName:"Nix Engineering",
 protections:[
 { id:"nix-flake-lock", match:/(?:^|\/)flake\.lock$/iu, reason:"flake.lock is generated by Nix flake commands.", recovery:"Change flake inputs and regenerate the lock with Nix." },
],
 validators:[
 { id:"nixParse", kind:"nix", match:/\.nix$/iu, mode:"block" },
 { id:"flakeJson", kind:"json", match:/(?:^|\/)flake\.lock$/iu, mode:"block" },
],
};
