import { isRecord } from "@harness/core/hook-event";

const LOCKFILE_GROUPS = [
  {
    id: "javascript-lockfiles",
    names: [
      "bun.lock",
      "bun.lockb",
      "deno.lock",
      "npm-shrinkwrap.json",
      "package-lock.json",
      "pnpm-lock.yaml",
      "yarn.lock",
    ],
    reason: "JavaScript/TypeScript lockfiles are generated by their package managers",
    recovery: "Change the dependency declaration, then regenerate the lockfile with npm, pnpm, yarn, bun, or deno.",
  },
  {
    id: "python-lockfiles",
    names: ["pdm.lock", "Pipfile.lock", "poetry.lock", "uv.lock"],
    reason: "Python lockfiles are generated by their package managers",
    recovery: "Change the dependency declaration, then regenerate the lockfile with pdm, pipenv, poetry, or uv.",
  },
  {
    id: "php-ruby-lockfiles",
    names: ["composer.lock", "Gemfile.lock"],
    reason: "Composer/Bundler lockfiles are generated by their package managers",
    recovery: "Change the dependency declaration, then regenerate the lockfile with Composer or Bundler.",
  },
  {
    id: "compiled-language-lockfiles",
    names: [
      "Cargo.lock",
      "go.sum",
      "gradle.lockfile",
      "packages.lock.json",
    ],
    reason: "Dependency resolution or checksum files are generated by the language toolchain",
    recovery: "Change the dependency declaration, then regenerate the file with Cargo, Go, Gradle, or NuGet.",
  },
  {
    id: "platform-lockfiles",
    names: [
      ".terraform.lock.hcl",
      "flake.lock",
      "mix.lock",
      "renv.lock",
    ],
    reason: "Dependency state files are generated by the platform toolchain",
    recovery: "Change the dependency declaration, then regenerate the file with Terraform/OpenTofu, Nix, Mix, or renv.",
  },
  {
    id: "mobile-lockfiles",
    names: ["Package.resolved", "Podfile.lock", "pubspec.lock"],
    reason: "Mobile dependency state files are generated by their package managers",
    recovery: "Change the dependency declaration, then regenerate the file with SwiftPM, CocoaPods, or Dart/Flutter pub.",
  },
];

export type ProtectionMode = "block" | "allow";

export type ProtectionRule = {
  id: string;
  match: RegExp;
  mode: ProtectionMode;
  reason?: string;
  recovery?: string;
};

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/gu, "\\$&");
}

function fileNamePattern(names: readonly string[]): RegExp {
  return new RegExp(
    `(?:^|/)(?:${names.map(escapeRegExp).join("|")})$`,
    "iu",
  );
}

export const BUILTIN_RULES: ProtectionRule[] = [
  ...LOCKFILE_GROUPS.map((group) => ({
    id: group.id,
    match: fileNamePattern(group.names),
    mode: "block" as const,
    reason: group.reason,
    recovery: group.recovery,
  })),
  {
    id: "gradle-dependency-lockfiles",
    match: /(?:^|\/)gradle\/dependency-locks\/[^/]+\.lockfile$/iu,
    mode: "block",
    reason: "The Gradle dependency-locks directory is maintained by Gradle",
    recovery: "Change the Gradle dependency declaration, then regenerate it through Gradle dependency locking.",
  },
  {
    id: "dependency-directories",
    match:
      /(?:^|\/)(?:bower_components|jspm_packages|node_modules|vendor|\.venv|venv|__pypackages__|Pods|\.terraform|\.dart_tool|\.gradle)(?:\/|$)/iu,
    mode: "block",
    reason: "The target is inside a package-manager-owned third-party dependency directory",
    recovery: "Change the dependency declaration, patch source, or project source, then reinstall dependencies with the relevant package manager.",
  },
  {
    id: "nested-dependency-directories",
    match:
      /(?:^|\/)(?:Carthage\/Build|\.build\/checkouts|\.nuget\/packages|renv\/library|packrat\/lib)(?:\/|$)/iu,
    mode: "block",
    reason: "The target is inside a package-manager-owned third-party dependency directory",
    recovery: "Change the dependency declaration, patch source, or project source, then reinstall dependencies with the relevant package manager.",
  },
];

function warnDefault(message: string): void {
  process.stderr.write(`[dependency-file-custody] ${message}\n`);
}

export function normalizeUserRule(
  rule: unknown,
  index: number,
  warn: (message: string) => void = warnDefault,
): ProtectionRule | null {
  if (!isRecord(rule) || !(rule.match instanceof RegExp)) {
    warn(`rule[${index}]: "match" must be a RegExp, skipping`);
    return null;
  }
  const mode = rule.mode ?? "block";
  if (mode !== "block" && mode !== "allow") {
    warn(`rule[${index}]: "mode" must be "block" or "allow", skipping`);
    return null;
  }
  for (const field of ["id", "reason", "recovery"] as const) {
    if (rule[field] !== undefined && typeof rule[field] !== "string") {
      warn(`rule[${index}]: "${field}" must be a string, skipping`);
      return null;
    }
  }
  const id = typeof rule.id === "string" && rule.id.trim() ? rule.id.trim() : `user-rule-${index + 1}`;
  const normalized: ProtectionRule = {
    id,
    match: rule.match,
    mode,
  };
  if (typeof rule.reason === "string") normalized.reason = rule.reason;
  if (typeof rule.recovery === "string") normalized.recovery = rule.recovery;
  return normalized;
}

export function resolveRules(
  userConfig: unknown,
  warn: (message: string) => void = warnDefault,
): ProtectionRule[] {
  if (!isRecord(userConfig)) return [...BUILTIN_RULES];
  if (userConfig.rules !== undefined && !Array.isArray(userConfig.rules)) {
    warn('config "rules" must be an array; using built-in rules');
    return [...BUILTIN_RULES];
  }
  const userRules = (Array.isArray(userConfig.rules) ? userConfig.rules : [])
    .map((rule, index) => normalizeUserRule(rule, index, warn))
    .filter((rule): rule is ProtectionRule => rule !== null);
  return [...userRules, ...BUILTIN_RULES];
}

function regexMatches(pattern: RegExp, value: string): boolean {
  try {
    return new RegExp(pattern.source, pattern.flags).test(value);
  } catch {
    return false;
  }
}

export function matchRule(matchPaths: readonly string[], rules: readonly ProtectionRule[]): ProtectionRule | null {
  for (const rule of rules) {
    if (matchPaths.some((path) => regexMatches(rule.match, path))) return rule;
  }
  return null;
}
