import assert from "node:assert/strict";
import test from "node:test";

import {
  REVIEW_INPUT_SCHEMA,
  computeTrainingSubjectDigest,
  createTrainingReceipt,
  validateTrainingModel,
} from "../src/lib/contract.js";
import {
  createRenderEvidence,
  renderTrainingMaterials,
  sealTrainingReview,
  validateReviewInput,
} from "../src/lib/pipeline.js";
import { sha256, sourceModel, validPlan } from "./fixture.js";

function hydrate(model: ReturnType<typeof sourceModel>) {
  model.digests = Object.fromEntries(Object.entries(model.files).map(([path, value]) => [path, sha256(value)]));
  return model;
}

function materialsModel() {
  const model = sourceModel();
  model.plan = { ...validPlan(model.artifactId, "materials") };
  Object.assign(model.files, renderTrainingMaterials(model));
  hydrate(model);
  model.files["evidence.render.json"] = `${JSON.stringify(createRenderEvidence(model), null, 2)}\n`;
  return hydrate(model);
}

function reviewInput() {
  return {
    schema: REVIEW_INPUT_SCHEMA,
    reviewer: { kind: "agent", id: "reviewer" },
    criteria: [
      "alignment",
      "audience-variability",
      "practice",
      "assessment",
      "facilitation",
      "material-consistency",
      "transfer",
    ].map((id) => ({ id, pass: true, evidence: `${id} is demonstrated by the named outcome and activity mappings.` })),
    findings: [],
  };
}

test("renders a complete current materials stage from one source", () => {
  const model = materialsModel();
  assert.deepEqual(validateTrainingModel(model, { stage: "materials" }), []);
  assert.match(model.files["dist/facilitator-guide.md"], /LO-1/u);
  assert.match(model.files["dist/learner-workbook.md"], /same representative workflow/iu);
});

test("source changes invalidate material evidence", () => {
  const model = materialsModel();
  model.training.title = "Changed after rendering";
  assert.ok(validateTrainingModel(model, { stage: "materials" }).some(({ code }) => code === "RENDER_EVIDENCE_INVALID"));
});

test("review input requires every quality criterion with evidence", () => {
  assert.deepEqual(validateReviewInput(reviewInput()), []);
  const invalid = reviewInput();
  invalid.criteria.pop();
  assert.ok(validateReviewInput(invalid).some(({ code }) => code === "REVIEW_CRITERION_MISSING"));
});

test("review and release bind current source and generated bytes", () => {
  const model = materialsModel();
  model.plan = { ...validPlan(model.artifactId, "release") };
  const review = sealTrainingReview(model, reviewInput(), { sessionId: "review-session", triggerFrom: "test:review" });
  model.files["review.training.json"] = `${JSON.stringify(review, null, 2)}\n`;
  hydrate(model);
  model.files["receipt.release.json"] = `${JSON.stringify(createTrainingReceipt(model), null, 2)}\n`;
  hydrate(model);

  assert.deepEqual(validateTrainingModel(model, { stage: "release" }), []);
  assert.equal(review.subjectDigest, computeTrainingSubjectDigest(model));

  model.files["dist/learner-workbook.md"] += "tampered\n";
  hydrate(model);
  assert.ok(validateTrainingModel(model, { stage: "release" }).some(({ code }) => ["RENDER_OUTPUT_STALE", "RECEIPT_INVALID"].includes(code)));
});
