import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { basename, dirname, extname, relative } from "node:path";
import { readState, writeState } from "../lib/state-store.mjs";

const TEXT_EXTENSIONS = new Set([".c", ".cc", ".cpp", ".cs", ".go", ".h", ".hpp", ".java", ".js", ".jsx", ".kt", ".kts", ".mjs", ".php", ".py", ".rs", ".swift", ".ts", ".tsx", ".vue", ".svelte", ".md", ".mdx", ".yaml", ".yml", ".tf"]);
function read(path, max = 8 * 1024 * 1024) { try { const text = readFileSync(path, "utf8"); return Buffer.byteLength(text) <= max ? text : null; } catch { return null; } }
function head(path) { try { const root = execFileSync("git", ["rev-parse", "--show-toplevel"], { cwd: dirname(path), encoding: "utf8", stdio: ["ignore", "pipe", "ignore"], timeout: 5000 }).trim(); const rel = relative(root, path).replaceAll("\\", "/"); return execFileSync("git", ["show", `HEAD:${rel}`], { cwd: root, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"], timeout: 5000 }); } catch { return ""; } }
function pair(path, input, current) { return { newer: typeof input.new_string === "string" ? input.new_string : current, older: typeof input.old_string === "string" ? input.old_string : head(path) }; }
function count(text, predicate) { return text.split(/\r?\n/u).filter(predicate).length; }
function debt(path, input, current) { const extension = extname(path).toLowerCase(); if (!TEXT_EXTENSIONS.has(extension)) return null; const { newer, older } = pair(path, input, current); const marker = extension === ".md" || extension === ".mdx" ? /\b(?:TODO|FIXME|HACK|WORKAROUND|TEMPORARY|XXX)\b\s*[:：(（]/iu : /\b(?:TODO|FIXME|HACK|WORKAROUND|TEMPORARY|XXX)\b/iu; const valid = /(?:ticket|issue|#[0-9]+|原因|reason|expires|过期|到期|偿还|remove after)/iu; const hits = (text) => count(text, (line) => marker.test(line) && !valid.test(line)); const net = hits(newer) - hits(older); return net > 0 ? `[Debt Marker Guard] ${path}: ${net} net-new debt marker(s) lack ticket, reason, expiry, or repayment condition` : null; }
function planDebt(path, input, current) { const normalized = path.replaceAll("\\", "/"); if (!/(?:^|\/)(?:PRD|prd|PLAN|plan|ROADMAP|roadmap|milestones?|risk-register|risks?)[^/]*\.md$|\/docs\/(?:requirements|plan|roadmap)\//u.test(normalized)) return null; const { newer, older } = pair(path, input, current), debtLine = /\b(?:TODO|TBD|待定|风险|Risk|blocker|阻塞)\b/iu, context = /\b(?:owner|负责人|status|状态|due|截止|date|日期|DoD|验收|AC|acceptance)\b/iu; const hits = (text) => count(text, (line) => debtLine.test(line) && !context.test(line)); const net = hits(newer) - hits(older); return net > 0 ? `[Plan Debt Guard] ${path}: ${net} new plan item(s) lack owner, status, due date, DoD, or acceptance criteria` : null; }

function stripJsonComments(text) { let out = "", string = false, escaped = false, line = false, block = false; for (let i = 0; i < text.length; i += 1) { const char = text[i], next = text[i + 1]; if (line) { if (char === "\n") { line = false; out += char; } continue; } if (block) { if (char === "*" && next === "/") { block = false; i += 1; } continue; } if (string) { out += char; if (escaped) escaped = false; else if (char === "\\") escaped = true; else if (char === '"') string = false; continue; } if (char === '"') { string = true; out += char; } else if (char === "/" && next === "/") { line = true; i += 1; } else if (char === "/" && next === "*") { block = true; i += 1; } else out += char; } return out; }
function jsonSyntax(path, text) { if (extname(path).toLowerCase() !== ".json") return null; const name = basename(path), jsonc = name === "jsconfig.json" || /^tsconfig(?:\..+)?\.json$/u.test(name) || /\/(?:\.devcontainer\/devcontainer|\.vscode\/(?:settings|extensions|launch|tasks))\.json$/u.test(path.replaceAll("\\", "/")); try { JSON.parse(jsonc ? stripJsonComments(text).replace(/,\s*([}\]])/gu, "$1") : text); return null; } catch (error) { return `[JSON Syntax] ${path}: ${error?.message ?? error}`; } }
function xmlSyntax(path) { if (extname(path).toLowerCase() !== ".xml") return null; try { execFileSync("xmllint", ["--noout", path], { stdio: ["ignore", "pipe", "pipe"], timeout: 8000 }); return null; } catch (error) { if (error?.code === "ENOENT") { const text = read(path, 2 * 1024 * 1024); if (!text) return null; const tags = [...text.replace(/<!--[\s\S]*?-->/gu, "").matchAll(/<\/?([A-Za-z_][\w:.-]*)\b[^>]*>/gu)]; const stack = []; for (const match of tags) { const token = match[0], name = match[1]; if (token.startsWith("</")) { if (stack.pop() !== name) return `[XML Syntax] ${path}: mismatched closing tag ${name}`; } else if (!token.endsWith("/>") && !token.startsWith("<?") && !token.startsWith("<!")) stack.push(name); } return stack.length ? `[XML Syntax] ${path}: unclosed tag ${stack.at(-1)}` : null; } const output = `${error?.stderr ?? error?.message ?? ""}`.trim(); return output ? `[XML Syntax] ${output.split("\n").slice(0, 10).join("\n")}` : null; } }
function estimateTokens(text) { let ascii = 0, other = 0; for (const char of text) if ((char.codePointAt(0) ?? 0) < 128) ascii += 1; else other += 1; return Math.ceil(ascii / 4) + other; }
function markdownBudget(path, current) { const normalized = path.replaceAll("\\", "/"), name = basename(path); let budget = null, label = ""; if (normalized.includes("/references/") && name.endsWith(".md")) { budget = 2000; label = "references"; } else if (name === "SKILL.md") { budget = 1500; label = "SKILL.md"; } else if (["MEMORY.md", "CLAUDE.md", "AGENTS.md"].includes(name)) { budget = 20000; label = "memory"; } if (!budget) return null; const now = estimateTokens(current); if (now <= budget) return null; const before = estimateTokens(head(path)); if (!before || before <= budget || now > before) return `[Markdown Budget] ${path}: ${label} is about ${now} tokens (budget ${budget}); new/ratcheted files must be reduced`; return now < before ? `[Markdown Budget] ${path}: reduced ${before - now} tokens but remains above ${budget}` : null; }
function editLoop(event, path) { if ([".md", ".mdx"].includes(extname(path).toLowerCase())) return null; const namespace = `edit-${createHash("sha256").update(path).digest("hex").slice(0, 16)}`, now = Date.now(), previous = readState(namespace, event, null), released = previous?.blocked === true, countValue = (!previous || now - previous.firstSeen > 30 * 60 * 1000 || released ? 0 : previous.count) + 1, firstSeen = !previous || now - previous.firstSeen > 30 * 60 * 1000 || released ? now : previous.firstSeen, state = { path, count: countValue, firstSeen, lastSeen: now, blocked: countValue >= 10 }; writeState(namespace, event, state); if (countValue >= 10) return `[Edit Loop] ${path} has been edited ${countValue} times in ${Math.round((now - firstSeen) / 1000)}s; stop, inspect full context and error evidence, then form one minimal change plan`; if (countValue >= 5) return `[Edit Loop] ${path} has been edited ${countValue} times; ${10 - countValue} more reaches the stop threshold`; return null; }

export function postFileReports(event, path, input = {}) { const current = read(path); if (current === null) return []; return [jsonSyntax(path, current), xmlSyntax(path), debt(path, input, current), planDebt(path, input, current), markdownBudget(path, current), editLoop(event, path)].filter(Boolean); }
