import { readState, writeState } from "../lib/state-store.mjs";

const HANGUL = /\p{Script=Hangul}/gu, JAPANESE = /[\p{Script=Hiragana}\p{Script=Katakana}]/gu, LETTER = /\p{L}/gu;
function state(event) { return readState("language", event, { authorized: [], toolFeedback: false, stopFeedback: false }); }
export function markLanguageIntent(event, prompt) { const current = state(event), authorized = new Set(current.authorized); if (/韩文|韩语|朝鲜语|\bKorean\b/iu.test(prompt)) authorized.add("korean"); if (/日文|日语|\bJapanese\b/iu.test(prompt)) authorized.add("japanese"); if (authorized.size === current.authorized.length) return false; writeState("language", event, { ...current, authorized: [...authorized] }); return true; }
function stripMarkdown(text) { return text.replace(/```[\s\S]*?```/gu, "").replace(/`[^`\n]*`/gu, "").replace(/^\s*>.*$/gmu, "").replace(/https?:\/\/\S+/gu, ""); }
function drift(text, language) { const pattern = language === "korean" ? HANGUL : JAPANESE, count = text.match(pattern)?.length ?? 0, letters = text.match(LETTER)?.length ?? 0; return count >= 12 && letters > 0 && count / letters >= 0.25 ? { language, count } : null; }
export function generatedText(event) { const input = event?.tool_input ?? event?.toolInput ?? event?.tool?.input ?? event?.input ?? {}, name = String(event?.tool_name ?? event?.toolName ?? event?.tool?.name ?? "").toLowerCase(); if (/bash|shell|exec/u.test(name)) return input.command ?? input.cmd ?? ""; if (/write/u.test(name)) return input.content ?? ""; if (/edit/u.test(name)) return input.new_string ?? ""; if (/patch/u.test(name)) return [input.patch, input.input, input.command].filter((value) => typeof value === "string").join("\n").split("\n").filter((line) => line.startsWith("+") && !line.startsWith("+++")).map((line) => line.slice(1)).join("\n"); return ""; }
export function languageDriftReport(event, text, surface = "tool", strip = false) { if (!text) return null; const current = state(event), authorized = new Set(current.authorized), candidate = strip ? stripMarkdown(text) : text; const finding = [drift(candidate, "korean"), drift(candidate, "japanese")].find((item) => item && !authorized.has(item.language)); if (!finding) return null; const key = surface === "stop" ? "stopFeedback" : "toolFeedback"; if (current[key]) return surface === "stop" ? `[Language Drift Gate] 已检测到未授权的 ${finding.language} 输出；本会话此前已反馈，本次仅记录以避免循环。` : null; writeState("language", event, { ...current, [key]: true }); return `[Language Drift Gate] 检测到未授权的 ${finding.language} 输出（${finding.count} 个脚本文字）。请保持用户当前语言；只有用户明确要求日语/韩语时才切换。`;
}
