import { createHash } from "node:crypto";
import { isAbsolute, relative, resolve, sep } from "node:path";
import { tokenizeShell } from "../lib/shell-parse.mjs";
import { readState, updateState, writeState } from "../lib/state-store.mjs";

function finding(action, id, reason, recovery) { return { action, id, reason, recovery }; }
function digest(value) { return createHash("sha256").update(value).digest("hex").slice(0, 16); }
function writeTargets(event) { const input = event?.tool_input ?? event?.toolInput ?? event?.tool?.input ?? event?.input ?? {}; const targets = [input.file_path, input.filePath, input.path, input.target_file, ...(event?.tool?.fileTargets ?? [])]; const patch = [input.patch, input.input, input.command].filter((value) => typeof value === "string").join("\n"); for (const match of patch.matchAll(/^\*\*\*\s+(?:Add|Update|Delete) File:\s+(.+)$/gmu)) targets.push(match[1].trim()); return [...new Set(targets.filter(Boolean))]; }
function content(event) { const input = event?.tool_input ?? event?.toolInput ?? event?.tool?.input ?? event?.input ?? {}; return [input.new_string, input.content, ...(Array.isArray(input.edits) ? input.edits.map((edit) => edit?.new_string) : []), input.patch].filter((value) => typeof value === "string").join("\n"); }

function backup(event) { for (const target of writeTargets(event)) { const path = String(target).replaceAll("\\", "/"); if (/(?:^|\/)(?:src|tests?|app|lib|packages|components)\//iu.test(path) && /(?:~|\.(?:bak|backup|old|orig|rej|tmp|swp|swo))$/iu.test(path) && !/(?:^|\/)(?:dist|build|vendor|node_modules|target)\//iu.test(path)) return finding("deny", "Backup Artifact Guard", `源码/测试目录禁止备份产物：${target}`, "直接修改目标文件；对照使用 git diff、stash 或系统临时目录"); } return null; }
function garbled(event) { const text = content(event), count = text.match(/\uFFFD/gu)?.length ?? 0; return /\uFFFD{2,}/u.test(text) || count >= 3 ? finding("deny", "Garbled Text Guard", `写入内容包含 ${count} 个 U+FFFD 替换字符`, "重新生成干净文本后再写入") : null; }

function externalSkill(command, event) {
  const install = /\b(?:(?:npx|pnpm\s+dlx|yarn\s+dlx|bunx)(?:\s+-\S+)*|npm\s+exec(?:\s+-\S+)*(?:\s+--)?)\s+skills\s+(?:add|install)\b|\bskills\s+(?:add|install)\b|\bgh\s+skill\s+install\b/iu.test(command);
  const global = /(?:^|\s)(?:-g|--global)(?:\s|$)|(?:^|\s)--scope\s+(?:user|global)(?:\s|$)|(?:~\/\.claude\/skills|~\/\.agents\/skills|~\/\.codex\/skills)\b/iu.test(command); if (install && global) return finding("deny", "External Skill Global Install Guard", `外部 skill 全局安装扩大供应链和持久化风险（摘要 ${digest(command)}）`, "先用 find-skill 隔离发现和静态审计");
  const findScope = /find-skill/u.test(JSON.stringify(event)) || process.env.AI_EXPERTS_ACTIVE_SKILL === "find-skill";
  const clone = /\b(?:git|gh\s+repo)\s+clone\b/iu.test(command);
  const dependencyInstall = packageCommandTargets(command, event?.cwd ?? process.cwd(), new Set(["add", "ci", "i", "install"])).length > 0;
  const externalRun = packageCommandTargets(command, event?.cwd ?? process.cwd(), new Set(["run"])).some((target) => outside(event?.cwd ?? process.cwd(), target));
  if (findScope && (clone || install || dependencyInstall || externalRun) && !/(?:^|\s)(?:--list|list|--dry-run|--help|-h)(?:\s|$)/u.test(command)) return finding("deny", "External Skill Isolation Guard", "find-skill 期间禁止直接拉取、安装或执行第三方候选", "使用 external-skill-static-audit 在临时目录静态审计");
  return install ? finding("report", "External Skill Install Notice", `检测到非全局外部 skill 安装（摘要 ${digest(command)}）`, "在临时或项目隔离目录审计，不执行生命周期脚本") : null;
}

const PACKAGE_MANAGERS = new Set(["npm", "pnpm", "yarn", "bun"]), PACKAGE_CWD_FLAGS = new Set(["--cwd", "--prefix", "--dir", "-C"]), COMMAND_SEPARATORS = new Set(["&&", "||", ";", "|"]);
function outside(workspace, target) { const value = relative(resolve(workspace), resolve(target)); return value === ".." || value.startsWith(`..${sep}`) || isAbsolute(value); }
function packageCommandTargets(command, fallbackCwd, accepted) {
  const tokens = tokenizeShell(command), targets = [];
  for (let index = 0; index < tokens.length; index += 1) {
    if (!PACKAGE_MANAGERS.has(tokens[index])) continue;
    const segment = []; for (let cursor = index + 1; cursor < tokens.length && !COMMAND_SEPARATORS.has(tokens[cursor]); cursor += 1) segment.push(tokens[cursor]);
    let subcommand = null; for (let cursor = 0; cursor < segment.length; cursor += 1) { const token = segment[cursor]; if (token === "--") break; if (PACKAGE_CWD_FLAGS.has(token)) { cursor += 1; continue; } if ([...PACKAGE_CWD_FLAGS].some((flag) => token.startsWith(`${flag}=`)) || token.startsWith("-")) continue; subcommand = token; break; }
    if (!subcommand || !accepted.has(subcommand)) continue;
    let target = fallbackCwd; for (let cursor = 0; cursor < segment.length; cursor += 1) { const token = segment[cursor]; if (PACKAGE_CWD_FLAGS.has(token) && segment[cursor + 1]) target = resolve(fallbackCwd, segment[cursor + 1]); const inline = [...PACKAGE_CWD_FLAGS].find((flag) => token.startsWith(`${flag}=`)); if (inline) target = resolve(fallbackCwd, token.slice(inline.length + 1)); }
    targets.push(target);
  }
  return targets;
}

function taskLedger(event, command) { const targets = writeTargets(event).map(String), tool = String(event?.tool_name ?? event?.toolName ?? event?.tool?.name ?? ""); const direct = targets.some((path) => /(?:^|[/\\])\.task-ledgers(?:[/\\]|$)/u.test(path)) && /write|edit|patch|delete|remove|move|copy|rename/iu.test(tool); const shell = /\.task-ledgers/u.test(command) && /(?:^|[\s;&|])(?:tee|touch|truncate|cp|mv|install|rm|unlink|dd|mkdir|rmdir|chmod|chown|sed|perl|node|python\d*|ruby|php|bash|sh|tsx|bun|deno|git\s+(?:checkout|restore|clean))\b|(?:^|[^<])>{1,2}(?!>)/u.test(command) && !/\blong-task-ledger\b[^\n;&|]*\s--action(?:=|\s+)(?:init|update|repair)\b/u.test(command); return direct || shell ? finding("deny", "Task Ledger Mutation Guard", "禁止直接写入 .task-ledgers", "使用 long-task-ledger --action init|update 或带哈希 repair") : null; }

export function normalizeCommand(command) { let value = command.replace(/\s+#\s*retry-ok\b.*$/iu, "").trim().replace(/\s+2>&1/gu, " ").replace(/\s+(?:1>>|2>>|1>|2>|>>|>)\s*(?:"[^"]+"|'[^']+'|\S+)\s*$/gu, ""); while (/\s*\|\s*(?:tail|head|less|more|tee|cat)\b[^|]*$/iu.test(value)) value = value.replace(/\s*\|\s*(?:tail|head|less|more|tee|cat)\b[^|]*$/iu, "").trim(); return value.replace(/\s+/gu, " ").replace(/;+$/u, "").trim(); }
function stripAssignments(command) { let value = command.trim(); while (/^[A-Za-z_][A-Za-z0-9_]*=(?:"[^"]*"|'[^']*'|\S+)\s+/u.test(value)) value = value.replace(/^[A-Za-z_][A-Za-z0-9_]*=(?:"[^"]*"|'[^']*'|\S+)\s+/u, ""); return value; }
function readOnly(command) { const value = stripAssignments(command), subshell = command.trim().match(/^[A-Za-z_][A-Za-z0-9_]*=\$\(([\s\S]*)\)$/u); return /^\s*(?:ls|cat|head|tail|echo|pwd|which|wc|find|grep|rg|git\s+(?:status|diff|log|show|ls-files))\b/iu.test(value) || Boolean(subshell && /^\s*(?:ls|cat|head|tail|echo|pwd|which|wc|find|grep|rg|git\s+(?:status|diff|log|show|ls-files))\b/iu.test(stripAssignments(normalizeCommand(subshell[1])))); }
function retry(event, command) { if (/#\s*retry-ok\b/iu.test(command) || readOnly(command)) return null; const normalized = normalizeCommand(command), state = readState("retry", event, null); if (!state || Date.now() - state.lastSeen > 10 * 60 * 1000 || state.normalized !== normalized) return null; const streak = state.lastOutcome === "failure" ? state.failStreak + 1 : state.successStreak + 1, block = state.lastOutcome === "failure" ? 5 : 12, report = state.lastOutcome === "failure" ? 3 : 6; if (streak >= block) return finding("deny", "Error Retry Guard", `${state.lastOutcome === "failure" ? "失败" : "成功"}后重复同一命令 ${streak} 次`, "分析上次结果并改变代码/环境；确属预期时加 # retry-ok"); if (streak >= report) return finding("report", "Error Retry Guard", `同一命令已连续${state.lastOutcome === "failure" ? "失败" : "成功"} ${streak} 次`, `再重复 ${block - streak} 次将阻断`); return null; }
export function recordOutcome(event, command, outcome) { if (!command) return; if (/#\s*retry-ok\b/iu.test(command)) { writeState("retry", event, null); return; } if (readOnly(command)) return; const normalized = normalizeCommand(command), now = Date.now(); updateState("retry", event, null, (previous) => previous && now - previous.lastSeen <= 10 * 60 * 1000 && previous.normalized === normalized ? { normalized, failStreak: outcome === "failure" ? (previous.lastOutcome === "failure" ? previous.failStreak + 1 : 1) : 0, successStreak: outcome === "success" ? (previous.lastOutcome === "success" ? previous.successStreak + 1 : 1) : 0, lastOutcome: outcome, lastSeen: now } : { normalized, failStreak: outcome === "failure" ? 1 : 0, successStreak: outcome === "success" ? 1 : 0, lastOutcome: outcome, lastSeen: now }); }

function sleepEstimate(command) { let total = [...command.matchAll(/\bsleep\s+(\d+(?:\.\d+)?)\b/gu)].reduce((sum, match) => sum + Number(match[1]), 0); const range = command.match(/\bfor\s+\w+\s+in\s+\{(\d+)\.\.(\d+)\}/u); if (range) total *= Math.max(1, Number(range[2]) - Number(range[1]) + 1); else if (/\bwhile\s+/u.test(command)) total *= 10; return Math.min(total, 3600); }
function polling(event, command) { if (/#\s*poll-ok\b/iu.test(command)) return null; const sleep = sleepEstimate(command), poll = /\b(?:glab\s+(?:ci\s+(?:list|status|get|view|trace)|api\s+\S*(?:pipeline|job|release|deploy)s?)|gh\s+(?:run\s+(?:list|view|watch)|pr\s+checks|workflow\s+view))\b/iu.test(command) ? 1 : 0; if (!sleep && !poll) return null; const now = Date.now(), next = updateState("polling", event, { entries: [], lastReportAt: 0 }, (state) => { const entries = (state?.entries ?? []).filter((entry) => now - entry.at <= 30 * 60 * 1000); entries.push({ at: now, sleep, poll }); return { entries, lastReportAt: state?.lastReportAt ?? 0 }; }); const sleepSum = next.entries.reduce((sum, entry) => sum + entry.sleep, 0), pollSum = next.entries.reduce((sum, entry) => sum + entry.poll, 0); if ((sleepSum >= 600 || pollSum >= 20) && now - next.lastReportAt >= 5 * 60 * 1000) { next.lastReportAt = now; writeState("polling", event, next); return finding("report", "Polling Budget", `近 30 分钟累计 sleep ${Math.round(sleepSum)}s、远端查询 ${pollSum} 次`, "使用 bounded watch/MCP，或明确总预算、递增间隔和超时分支"); } return null; }

export function preDisciplineFindings(event, command = "") { return [backup(event), garbled(event), externalSkill(command, event), taskLedger(event, command), retry(event, command), polling(event, command)].filter(Boolean); }
export function disciplineMessage(item) { return [`[${item.id}] ${item.action === "deny" ? "已拦截" : "提示"}`, "", `原因：${item.reason}`, `恢复/替代：${item.recovery}`, ...(item.action === "deny" ? ["", "blockingContract:", "  observedFacts: 当前操作违反执行纪律或受管状态边界。", "  harm: 可能制造不可审计状态、重复失败、供应链风险或临时产物。", "  unblockWhen: 使用受控工具、修正输入或先完成根因分析。", `  recovery: ${item.recovery}`] : [])].join("\n"); }
