import type { DomainEngineeringPolicy } from "@harness/core/domain-engineering-hook";

export const policy: DomainEngineeringPolicy = {
 plugin:"kubernetes-operations",
 displayName:"Kubernetes Operations",
 protections:[
 { id:"helm-lock", match:/(?:^|\/)Chart\.lock$/iu, reason:"Chart.lock is generated by Helm dependency management.", recovery:"Change Chart.yaml and regenerate dependencies with Helm." },
 { id:"helm-vendored-charts", match:/(?:^|\/)charts(?:\/|$)/iu, reason:"Vendored Helm charts are dependency-manager-owned.", recovery:"Change Chart.yaml and use Helm dependency commands." },
],
 validators:[
 { id:"kubernetesDryRun", kind:"kubectl", match:/\.ya?ml$/iu, contentMatch:/^\s*apiVersion\s*:[\s\S]*^\s*kind\s*:/imu, mode:"report" },
 { id:"helmLint", kind:"helm", match:/(?:^|\/)Chart\.yaml$/iu, mode:"report" },
 { id:"kubernetesJson", kind:"json", match:/\.json$/iu, mode:"block" },
],
};
