import { repoContainsPath, type DomainEngineeringPolicy } from "@harness/core/domain-engineering-hook";

export const policy: DomainEngineeringPolicy = {
 plugin:"java-engineering",
 displayName:"Java Engineering",
 active:(context)=>/(?:^|\/)pom\.xml$/iu.test(context.relativePath)||!repoContainsPath(context.root,/(?:^|\/)AndroidManifest\.xml$/iu),
 protections:[
 { id:"java-gradle-locks", match:/(?:^|\/)gradle\.lockfile$|(?:^|\/)gradle\/dependency-locks\/[^/]+\.lockfile$/iu, reason:"JVM dependency locks are generated by Gradle.", recovery:"Change Gradle declarations and regenerate locks through the wrapper." },
 { id:"java-gradle-cache", match:/(?:^|\/)\.gradle(?:\/|$)/iu, reason:"The Gradle cache is tool-owned.", recovery:"Change sources or declarations and let Gradle rebuild the cache." },
],
 validators:[
 { id:"mavenXml", kind:"xml", match:/(?:^|\/)pom\.xml$/iu, mode:"block" },
],
};
