import { packageDeclaresDependency, type DomainEngineeringPolicy } from "@harness/core/domain-engineering-hook";

export const policy: DomainEngineeringPolicy = {
 plugin:"react-native-engineering",
 displayName:"React Native Engineering",
 active:(context)=>packageDeclaresDependency(context,"react-native")||/(?:^|\/)(?:NativeComponent\.g\.(?:h|mm)|android\/.+\/build\/generated\/source\/codegen|ios\/build\/generated\/ios)(?:\/|$)/iu.test(context.relativePath),
 protections:[
 { id:"react-native-lockfiles", match:/(?:^|\/)(?:bun\.lockb?|npm-shrinkwrap\.json|package-lock\.json|pnpm-lock\.yaml|yarn\.lock)$/iu, reason:"React Native JavaScript lockfiles are generated by package managers.", recovery:"Change package.json and regenerate the lock with the project's package manager." },
 { id:"react-native-dependencies", match:/(?:^|\/)node_modules(?:\/|$)/iu, reason:"node_modules is package-manager-owned.", recovery:"Change sources or declarations and reinstall dependencies." },
 { id:"react-native-codegen", match:/(?:^|\/)(?:NativeComponent\.g\.(?:h|mm)|android\/.+\/build\/generated\/source\/codegen|ios\/build\/generated\/ios)(?:\/|$)/iu, reason:"React Native Codegen output is generated from schemas.", recovery:"Change the schema or native component source and rerun Codegen." },
],
 validators:[
 { id:"reactNativeConfig", kind:"javascript", match:/(?:^|\/)(?:metro|babel|react-native)\.config\.(?:c?js|mjs)$/iu, mode:"block" },
 { id:"reactNativeTypescript", kind:"typescript", match:/\.(?:ts|tsx)$/iu, mode:"block" },
 { id:"reactNativeJson", kind:"json", match:/(?:^|\/)(?:package|app)\.json$/iu, mode:"block" },
],
};
