import type { DomainEngineeringPolicy, DomainSourceScanHit } from "@harness/core/domain-engineering-hook";

function unexplainedUnsafeHits(_filePath: string, source: string): DomainSourceScanHit[] {
  const lines = source.split(/\r?\n/u);
  return lines.flatMap((raw, index) => {
    const codeOnly = raw.replace(/"(?:\\.|[^"\\])*"/gu, "\"\"").replace(/\/\/.*$/u, "");
    const occurrences = [...codeOnly.matchAll(/\bunsafe\s+(?:fn\b|\{)/gu)];
    if (!occurrences.length) return [];
    const context = lines.slice(Math.max(0, index - 3), index + 1).join("\n");
    if (/\bSAFETY\s*:/u.test(context)) return [];
    return occurrences.map(() => ({ line: index + 1, code: "UNEXPLAINED_UNSAFE", message: "Document the local SAFETY invariant immediately above the unsafe function or block." }));
  });
}

export const policy: DomainEngineeringPolicy = {
 plugin:"rust-engineering",
 displayName:"Rust Engineering",
 protections:[
 { id:"cargo-lock", match:/(?:^|\/)Cargo\.lock$/iu, reason:"Cargo.lock is generated by Cargo.", recovery:"Change Cargo.toml and regenerate the lock with Cargo." },
],
 validators:[
 { id:"rustfmt", enforcement:"advisory", kind:"rustfmt", match:/\.rs$/iu, mode:"report" },
],
 sourceScans:[
 { id:"unsafeWithoutSafety", enforcement:"advisory", match:/\.rs$/iu, mode:"report", inspect:unexplainedUnsafeHits },
 ],
};
