import { packageDeclaresDependency, type DomainEngineeringPolicy } from "@harness/core/domain-engineering-hook";

export const policy: DomainEngineeringPolicy = {
 plugin:"web-frontend-engineering",
 displayName:"Web Frontend Engineering",
 active:(context)=>!packageDeclaresDependency(context,"react-native"),
 protections:[
 { id:"javascript-lockfiles", match:/(?:^|\/)(?:bun\.lockb?|deno\.lock|npm-shrinkwrap\.json|package-lock\.json|pnpm-lock\.yaml|yarn\.lock)$/iu, reason:"JavaScript lockfiles are generated by package managers.", recovery:"Change package.json and regenerate with npm, pnpm, yarn, bun, or deno." },
 { id:"javascript-dependencies", match:/(?:^|\/)node_modules(?:\/|$)/iu, reason:"node_modules is package-manager-owned.", recovery:"Change sources or declarations and reinstall dependencies." },
],
 validators:[
 { id:"javascriptSyntax", kind:"javascript", match:/\.(?:cjs|js|mjs)$/iu, mode:"block" },
 { id:"typescriptSyntax", kind:"typescript", match:/\.(?:cts|mts|ts|tsx)$/iu, mode:"block" },
 { id:"eslint", kind:"eslint", match:/\.(?:cjs|cts|js|jsx|mjs|mts|ts|tsx)$/iu, mode:"report" },
 { id:"packageJson", kind:"json", match:/(?:^|\/)package\.json$/iu, mode:"block" },
],
};
