import { repoContainsPath, type DomainEngineeringPolicy } from "@harness/core/domain-engineering-hook";

export const policy: DomainEngineeringPolicy = {
 plugin:"android-engineering",
 displayName:"Android Engineering",
 active:(context)=>/(?:AndroidManifest\.xml|res\/.+\.xml)$/iu.test(context.relativePath)||repoContainsPath(context.root,/(?:^|\/)AndroidManifest\.xml$/iu),
 protections:[
 { id:"android-gradle-locks", match:/(?:^|\/)gradle\.lockfile$|(?:^|\/)gradle\/dependency-locks\/[^/]+\.lockfile$/iu, reason:"Android dependency locks are generated by Gradle.", recovery:"Change Gradle dependency declarations and regenerate locks through the project wrapper." },
 { id:"android-gradle-cache", match:/(?:^|\/)\.gradle(?:\/|$)/iu, reason:"The Android Gradle cache is tool-owned.", recovery:"Change sources or declarations and let Gradle recreate the cache." },
],
 validators:[
 { id:"androidXml", kind:"xml", match:/(?:AndroidManifest\.xml|res\/.+\.xml)$/iu, mode:"block" },
 { id:"androidJson", kind:"json", match:/(?:^|\/)(?:google-services|package)\.json$/iu, mode:"block" },
],
};
