import { existsSync, readFileSync } from "node:fs";
import { basename, dirname, extname, join, resolve } from "node:path";
import { toolInput, writeTargets } from "../lib/hook-io.mjs";

const GENERATED = /(?:^|\/)(?:dist|build|vendor|node_modules|target|coverage|\.next|\.nuxt)(?:\/|$)/u;
function bytes(path, max = 8 * 1024 * 1024) { try { const value = readFileSync(path); return value.length <= max ? value : null; } catch { return null; } }
function text(path) { const value = bytes(path); if (!value) return null; try { return new TextDecoder("utf-8", { fatal: true }).decode(value); } catch { return null; } }
function encoding(path) { if (!/\.(?:md|txt|rst|adoc|xml|xsl|xsd)$/iu.test(path)) return null; const value = bytes(path); if (!value) return null; if (value.subarray(0, 3).equals(Buffer.from([0xef, 0xbb, 0xbf]))) return `[Documents Encoding Guard] ${path}: 检测到 UTF-8 BOM`; try { new TextDecoder("utf-8", { fatal: true }).decode(value); return null; } catch { return `[Documents Encoding Guard] ${path}: 文档不是有效 UTF-8`; } }
const ROUTES = [/\b(?:app|router|server)\s*\.\s*(?:get|post|put|patch|delete|head|options|all)\s*\(\s*['"`]/iu, /\b(?:http\.Handle|mux\.Handle|router\.(?:GET|POST|PUT|PATCH|DELETE|Handle)|r\.(?:GET|POST|PUT|PATCH|DELETE))\s*\(/u, /(?:@app\.(?:route|get|post|put|patch|delete)|@router\.(?:get|post|put|patch|delete)|path\s*\()/iu, /Route\s*::\s*(?:get|post|put|patch|delete|any|match)\s*\(/iu, /^\s*(?:\/[\w\-{}/]+)\s*:\s*$/u, /^\s+(?:get|post|put|patch|delete|head|options)\s*:\s*$/iu];
function routeLines(value) { return new Set(String(value ?? "").split("\n").map((line) => line.trim()).filter((line) => line && ROUTES.some((pattern) => pattern.test(line)))); }
function api(path, input) { const normalized = path.replaceAll("\\", "/").toLowerCase(), name = basename(path).toLowerCase(); if (!/(?:^|\/)(?:routes?|handlers?|controllers?)\//u.test(normalized) && !/^(?:openapi|swagger)\.(?:ya?ml|json)$/u.test(name) && !/\/api\/.*\.(?:ya?ml|json)$/u.test(normalized) || typeof input.old_string !== "string") return null; const old = routeLines(input.old_string), next = routeLines(input.new_string ?? ""), removed = [...old].filter((line) => !next.has(line)); return removed.length ? [`[API Breaking Change Guard] ${path} 检测到 ${removed.length} 个路由定义被删除：`, ...removed.slice(0, 5).map((line) => `- ${line}`), "请标注 BREAKING CHANGE、评估 major bump，并更新迁移与客户端文档。"].join("\n") : null; }
function docs(path, value) { if (!/\.(?:md|mdx|markdown)$/iu.test(path) || GENERATED.test(path.replaceAll("\\", "/"))) return null; const missing = []; for (const match of value.matchAll(/!?\[[^\]]+\]\(([^)\s]+)(?:\s+"[^"]*")?\)/gu)) { const target = match[1]; if (!target || target.startsWith("#") || target.startsWith("mailto:") || target.startsWith("//") || /^[a-z][a-z0-9+.-]*:/iu.test(target)) continue; const local = target.split("#", 1)[0].split("?", 1)[0]; if (local && !existsSync(resolve(dirname(path), local))) missing.push(target); } return missing.length ? [`[Docs Consistency Guard] ${path} 包含 ${missing.length} 个不存在的本地引用：`, ...missing.slice(0, 10).map((item) => `- ${item}`)].join("\n") : null; }
function designDoc(path) { let current = dirname(resolve(path)); for (let depth = 0; depth < 10; depth += 1) { const candidate = join(current, "DESIGN.md"); if (existsSync(candidate)) return candidate; const parent = dirname(current); if (parent === current) break; current = parent; } return null; }
function literals(value) { return new Set([...String(value ?? "").matchAll(/#[0-9a-f]{3,8}\b|rgba?\([^)]{1,80}\)|\b\d+(?:\.\d+)?(?:px|rem)\b/giu)].map((match) => match[0].toLowerCase())); }
function design(path, input, current) { if (!/\.(?:css|scss|sass|less|styl|jsx|tsx|vue|svelte)$/iu.test(path) || /(?:tokens?|theme|variables?)\.(?:css|scss|sass|less|js|ts)$/iu.test(path)) return null; const doc = designDoc(path); if (!doc) return null; const contract = text(doc); if (!contract) return `[Design Contract Drift Guard] ${doc} 没有可读取的设计契约，已 fail-open。`; const baseline = literals(input.old_string ?? ""), next = literals(input.new_string ?? current), allowed = literals(contract), added = [...next].filter((item) => !baseline.has(item) && !allowed.has(item)); return added.length ? `[Design Contract Drift Guard] ${path} 新增未在 DESIGN.md 声明的高置信度视觉字面量：${added.slice(0, 8).join("、")}。请使用项目 token/theme，或先更新 DESIGN.md。` : null; }
export function postReports(event) { const input = toolInput(event), reports = []; for (const path of writeTargets(event)) { if (!existsSync(path)) continue; const current = text(path), candidates = [encoding(path), api(path, input), current === null ? null : docs(path, current), current === null ? null : design(path, input, current)].filter(Boolean); reports.push(...candidates); } return reports; }
