import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { existsSync, lstatSync, readFileSync, readdirSync, realpathSync } from "node:fs";
import { dirname, isAbsolute, join, relative, resolve, sep } from "node:path";
import { activeSkills, completionStatus, finalText, missingTools, receiptInvocation, receiptPassed, receiptTool, receipts, recovery, successful, tagMap } from "../lib/evidence.mjs";
import { cwd } from "../lib/hook-io.mjs";
import { tddState } from "./tdd.mjs";

function gate(title, details, missing, action) { return [`[${title}] ${details}`, "", recovery(missing, action)].join("\n"); }
function nextSection(text) { const match = /(?:^|\n)#{0,6}\s*(?:📌\s*)?下一步推荐\s*[:：]?/u.exec(text); if (!match) return ""; const rest = text.slice(match.index), boundary = /\n(?:#{1,6}\s|---)/u.exec(rest.slice(1)); return rest.slice(0, boundary ? boundary.index + 1 : rest.length); }
function recommendations(section) { return section.split("\n").map((line) => line.trim()).filter((line) => /^[-*]\s+/u.test(line)); }
function nextStepGate(text) { if (/(?:最终答案|Final answer)[：:]/u.test(text)) return null; const section = nextSection(text), status = completionStatus(text), interrupted = status === "blocked" || status === "needs-context" || /(?:阻塞|中断|暂停|blocked|interrupted)/iu.test(text), unverified = /(?:未验证|未运行|未执行|未跑|无法验证|incomplete|unverified)/iu.test(text), troubleshooting = /(?:根因|排障|诊断|troubleshoot)/iu.test(text); if (!interrupted && !unverified && !troubleshooting) return null; if (!section) return gate("Skill Next Step Gate", "当前阻塞、未验证或排查场景缺少必要的“下一步推荐”区块。", "恢复、补验或收尾路径。", "先执行自己能完成的可逆动作；剩余项用 1-2 条具体恢复/验证动作表达。"); const items = recommendations(section), noRecommendation = /本轮无推荐/u.test(section); if (interrupted && (!items.length || noRecommendation)) return "[Skill Next Step Gate] 阻塞/中断场景必须给出 1-3 条可执行恢复动作。"; if ((unverified || troubleshooting) && (!items.length || noRecommendation || items.length > 2 || !/(?:修复|回归|验证|复测|补测|提交)/u.test(section))) return "[Skill Next Step Gate] 未验证/排查场景须保留最多 2 条且包含修复或验证导向的动作。"; return null; }
function solvability(text) { const section = [nextSection(text), ...[/(?:^|\n)#{0,6}\s*未验证项\s*[:：]?/u, /(?:^|\n)#{0,6}\s*已知风险(?:\s*[:：]|\/)/u].map((pattern) => { const match = pattern.exec(text); return match ? text.slice(match.index).split(/\n#{1,6}\s|\n---/u, 1)[0] : ""; })].join("\n"); if (!section.trim() || !successful(text) && !nextSection(text)) return null; const actions = [["版本/发版", /bump|版本|version|release|打\s*tag/iu], ["git/MR/PR", /建分支|commit|push|\bMR\b|\bPR\b|merge\s*request|pull\s*request|提交|合并/iu], ["依赖/安装", /composer\s+(?:update|install|require)|npm\s+install|pnpm\s+install|yarn|依赖.*(?:升|更新|同步)/iu], ["验证/测试", /跑测试|phpstan|phpunit|pytest|ruff|eslint|lint|验证|verify|回归|补测/iu], ["工单", /(?:issue|work\s*item|工单).*(?:更新|关闭|评论)|(?:更新|关闭|评论).*(?:issue|work\s*item|工单)/iu]].filter(([, pattern]) => pattern.test(section)).map(([label]) => label); if (!actions.length || /需(?:.*?用户)?凭据|需要.*?token|需要.*?授权|需用户决策|需用户确认|不可逆|生产(?:环境|数据)|按用户要求|用户明确|先不要|暂停/iu.test(section)) return null; return gate("Next Step Solvability Gate", `下一步/未验证项中包含本应自行执行的可逆动作：${actions.join("、")}。`, "可逆收尾动作的真实执行结果。", "执行命中的验证、git、版本、依赖或工单动作；只有缺凭据、不可逆或需业务裁决时才交还用户。"); }

const CLAIM_RE = /(phpstan|phpunit|pest|pytest|ruff|eslint|tsc|type[-\s]?check|lint|单元测试|测试|回归(?:测试)?|verify|verification|CI|流水线|pipeline)([^\n]{0,24}?)(通过|✅|🟢|Pass|Passed|PASS\b|Success|SUCCESS|全绿|all\s*pass|绿灯)/giu;
function provenance(event, text) { if (!successful(text) || /(?:尚未|还没|未)(?:运行|执行|跑)|排障|探索性|未验证项\s*[:：]|未实跑|未运行验证/iu.test(text)) return null; const valid = new Set(receipts(event).filter(receiptPassed).flatMap((record) => { const tool = receiptTool(record), id = receiptInvocation(record); return tool && id ? [`${tool}@${id}`] : []; })), bare = []; for (const match of text.matchAll(CLAIM_RE)) { const local = text.slice(Math.max(0, match.index - 140), Math.min(text.length, match.index + match[0].length + 140)); if (/(?:未|没|不|无|失败|failed|error).{0,8}(?:通过|Pass|Success|绿灯)/iu.test(match[0]) || /\[(?:本地实测|CI\s*实测|远端\s*CI|本地验证|推断|未验证|实测)\]|`[^`]*(?:npm|pytest|ruff|eslint|tsc|go\s+test|cargo|glab)[^`]*`/u.test(local)) continue; const tags = tagMap(local); if ([...tags].some(([tool, ids]) => [...ids].some((id) => valid.has(`${tool}@${id}`)))) continue; bare.push(match[0].trim()); if (bare.length === 3) break; } return bare.length ? gate("Verification Provenance Gate", `验证通过断言缺少可核验证据：${bare.map((item) => `「${item}」`).join("、")}。`, "断言来源，无法区分本地实测、CI 实测或推断。", "运行验证并标注 [本地实测]/[CI 实测] 与命令摘要；不能运行则标 [推断] 或移入未验证项。") : null; }

const PLAN_SKILLS = new Set(["design-doc-protocol", "visual-brief-concretizer", "deck-storyboard-design", "video-storyboard-design"]), DESIGN_SKILLS = new Set(["design-review", "color-accessibility-review", "color-system-design", "data-color-design", "color-management", "vi-system-design", "logo-design", "logo-audit", "frontend-design-taste", "poster-template-engine", "social-card-authoring", "jetpack-compose-interface-design", "swiftui-interface-design", "flutter-interface-design", "react-native-interface-design", "tarojs-interface-design", "wechat-miniprogram-interface-design", "pptx-deck-authoring", "pptx-deck-production", "pptx-delivery", "motion-graphics-production", "remotion-video-production", "video-quality-review"]);
function designEvidence(event, text, active) { const hasDesign = [...active].some((skill) => DESIGN_SKILLS.has(skill)), hasPlan = [...active].some((skill) => PLAN_SKILLS.has(skill)); if (!successful(text) || !hasDesign && !hasPlan) return null; const tool = hasDesign ? "design-accessibility-evidence-gate" : "design-accessibility-plan-check", missing = missingTools(event, text, [tool], { evidenceKind: "verification", freshAfterMutation: true }); return missing.length ? gate("Design Accessibility Completion Gate", `完成态缺少当前会话的 ${tool} 收据与 MCP实测标签。`, "WCAG 2.2 AA+ 计划或最终 artifact 证据闭环。", `调用 ${tool}，修复 required criterion 或证据来源问题，并补入返回的 MCP实测标签。`) : null; }
const VIDEO_TOOLS = { "video-storyboard-design": ["video-storyboard-validate"], "remotion-video-production": ["video-storyboard-validate", "video-media-probe", "video-frame-sample"], "video-quality-review": ["video-media-probe", "video-frame-sample"] };
function videoEvidence(event, text, active) { if (!successful(text)) return null; const required = [...active].flatMap((skill) => VIDEO_TOOLS[skill] ?? []), missing = missingTools(event, text, [...new Set(required)], { evidenceKind: "verification", freshAfterMutation: true }); return required.length && missing.length ? gate("Video Production Evidence Gate", `完成态缺少视频证据：${missing.join("、")}。`, "当前职责所需的分镜合同、媒体探测或最终成片抽帧收据。", "调用缺失的验证型工具并把 invocation id 作为 MCP实测标签加入完成态。") : null; }
function gitlabEvidence(event, text, active) { if (!successful(text) || ![...active].some((skill) => ["all-in-one-review", "agentic-fix-review-gate"].includes(skill))) return null; const missing = missingTools(event, text, ["gitlab-work-items-comment", "gitlab-work-items-mr-note", "gitlab-work-items-update"], { evidenceKind: "mutation" }); return missing.length ? gate("GitLab Review Completion Gate", `缺少 GitLab 双写/状态推进证据：${missing.join("、")}。`, "Work Item comment、MR note 和状态更新的成功收据。", "完成缺失写回，并把返回的 invocation id 作为 MCP实测标签加入完成态。") : null; }

function safeArtifact(root, path) { const absolute = resolve(root, path), rel = relative(realpathSync(root), realpathSync(absolute)); if (!rel || rel === ".." || rel.startsWith(`..${sep}`) || isAbsolute(rel) || lstatSync(absolute).isSymbolicLink() || !lstatSync(absolute).isFile()) throw new Error(`artifact path escapes workspace or is not a regular file: ${path}`); return absolute; }
function proofObjects(value, found = []) { if (Array.isArray(value)) for (const item of value) proofObjects(item, found); else if (value && typeof value === "object") { if (typeof value.path === "string" && typeof value.sha256 === "string") found.push(value); for (const child of Object.values(value)) proofObjects(child, found); } return found; }
function pptx(event, text, active) { if (!successful(text) || !active.has("pptx-deck-authoring") && !active.has("pptx-delivery")) return null; const missing = missingTools(event, text, ["pptx-deck-authoring-pptx-release"], { evidenceKind: "mutation", effectScope: "local-artifact", freshAfterMutation: true }), tagged = /\[PPTX发布:([^\]\r\n]+)\]/u.exec(text)?.[1]?.trim(), errors = []; if (!tagged) errors.push("缺少 [PPTX发布:<manifest 相对路径>]"); else try { const root = realpathSync(resolve(cwd(event))), manifestPath = safeArtifact(root, tagged), manifest = JSON.parse(readFileSync(manifestPath, "utf8")), proofs = proofObjects(manifest); if (!proofs.length) errors.push("release manifest 不含 path/sha256 证据"); for (const proof of proofs) { const artifact = safeArtifact(root, resolve(dirname(manifestPath), proof.path)); if (createHash("sha256").update(readFileSync(artifact)).digest("hex") !== proof.sha256) errors.push(`${proof.path} SHA-256 不一致`); } } catch (error) { errors.push(error instanceof Error ? error.message : String(error)); } return missing.length || errors.length ? gate("PPTX Completion Gate", [...missing.map((item) => `缺少 ${item} 成功收据`), ...errors].join("；"), "正式 release 收据、PPTX/PDF/逐页证据和精确哈希。", "调用正式 PPTX release 工具，修复 manifest 或输出哈希，并补入 MCP实测与 PPTX发布标签。") : null; }

function parseTable(text) { const lines = text.split(/\r?\n/u), header = lines.findIndex((line) => /^\|\s*id\s*\|/iu.test(line)); if (header < 0) return []; return lines.slice(header + 2).filter((line) => /^\|/u.test(line)).map((line) => line.split("|").slice(1, -1).map((cell) => cell.trim())); }
function migrationLedger(event, text, active) { if (!successful(text) || !active.has("migration-parity-review")) return null; const root = cwd(event), explicit = [...new Set([...text.matchAll(/((?:\.\/)?\.migration-parity\/[a-z0-9]+(?:-[a-z0-9]+)*\.md)/gu)].map((match) => match[1]))], dir = join(root, ".migration-parity"); let paths = explicit; if (!paths.length && existsSync(dir)) paths = readdirSync(dir).filter((name) => /^[a-z0-9]+(?:-[a-z0-9]+)*\.md$/u.test(name)).map((name) => join(".migration-parity", name)); if (paths.length !== 1) return gate("Migration Parity Completion Gate", paths.length ? `存在多个候选账本：${paths.join("、")}` : "未发现迁移对齐账本。", "唯一、完整的迁移对齐账本。", "用 migration-parity-ledger 补齐矩阵，并在回复中引用唯一账本路径。"); try { const rows = parseTable(readFileSync(resolve(root, paths[0]), "utf8")), unverified = rows.filter((row) => row.some((cell) => cell === "unverified")).map((row) => row[0]); return unverified.length ? gate("Migration Parity Completion Gate", `仍有未验证单元：${unverified.join("、")}`, "全部矩阵单元的证据或有意差异决策。", "继续执行未验证单元并原子更新账本。") : null; } catch { return null; } }
function taskLedger(event, text, active) { if (!active.has("long-task-context-governance") || !completionStatus(text)) return null; const root = cwd(event), explicit = [...new Set([...text.matchAll(/((?:\.\/)?\.task-ledgers\/[a-z0-9]+(?:-[a-z0-9]+)*\.md)/gu)].map((match) => match[1]))], dir = join(root, ".task-ledgers"); let paths = explicit; if (!paths.length && existsSync(dir)) paths = readdirSync(dir).filter((name) => /^[a-z0-9]+(?:-[a-z0-9]+)*\.md$/u.test(name)).map((name) => join(".task-ledgers", name)); if (paths.length !== 1) return null; try { const content = readFileSync(resolve(root, paths[0]), "utf8"), rows = parseTable(content), state = completionStatus(text), violations = []; if (["done", "done-with-concerns"].includes(state)) { const unfinished = rows.filter((row) => row[2] !== "done"); if (unfinished.length) violations.push(`未完成分片：${unfinished.map((row) => `${row[0]}(${row[2]})`).join("、")}`); const noEvidence = rows.filter((row) => row[2] === "done" && (!row[3] || !row[4] || row[4] === "[]")); if (noEvidence.length) violations.push(`完成分片缺少 evidence/evidence_refs：${noEvidence.map((row) => row[0]).join("、")}`); } else { if (rows.some((row) => row[2] === "in_progress")) violations.push("中断前仍有 in_progress 分片"); if (!/^- next shard:\s*(?!无\s*$).+/mu.test(content)) violations.push("Resume.next shard 缺失"); if (!/^- recovery commands:\s*$[\s\S]*?^\s+-\s+\S+/mu.test(content)) violations.push("Resume.recovery commands 缺失"); } return violations.length ? gate("Task Ledger Completion Gate", violations.join("；"), "闭合分片及其 evidence refs，或可恢复 checkpoint。", "用 long-task-ledger 原子更新状态、证据、next shard 和 recovery commands。") : null; } catch { return null; } }
function tdd(event, text, active) { if (!successful(text) || !active.has("test-driven-development")) return null; const state = tddState(event), missing = [!state?.testEdited && "测试文件编辑", !state?.redSeen && "预期红灯", !state?.sourceEditedAfterRed && "红灯后的生产代码编辑", !state?.greenSeen && "实现后的绿灯"].filter(Boolean); return missing.length ? gate("TDD Sequence Completion Gate", `完成态缺少 red-green 顺序证据：${missing.join("、")}。`, "测试编辑、预期失败、最小实现和通过结果。", "补齐缺失环节并实际运行定向测试；必要时用 characterization test 重建红灯。") : null; }

function hasCiRule(root) { let current = root; for (let depth = 0; depth < 12; depth += 1) { for (const name of ["AGENTS.md", "CLAUDE.md"]) try { if (/(?:ci-gated-mr-workflow|CI-gated\s+MR|本地验证不能替代远端\s*CI|MR\s+pipeline.*(?:master|main|主分支)\s+pipeline)/isu.test(readFileSync(join(current, name), "utf8").slice(0, 128 * 1024))) return true; } catch {} const parent = dirname(current); if (parent === current) break; current = parent; } return false; }
function delivery(event, text) { if (!successful(text) || /DONE_WITH_CONCERNS/u.test(text) && /按用户明确要求|权限不足|凭据|Runner.*(?:故障|不可用)|外部阻塞|无远端|无\s*CI/iu.test(text)) return null; const root = cwd(event); let repo; try { repo = execFileSync("git", ["rev-parse", "--show-toplevel"], { cwd: root, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"], timeout: 5000 }).trim(); } catch { return null; } if (!existsSync(join(repo, ".gitlab-ci.yml")) && !existsSync(join(repo, ".gitlab-ci.yaml")) || !hasCiRule(repo)) return null; let remotes = "", status = "", ahead = "0", diff = ""; try { remotes = execFileSync("git", ["remote"], { cwd: repo, encoding: "utf8" }); status = execFileSync("git", ["status", "--porcelain"], { cwd: repo, encoding: "utf8" }); ahead = execFileSync("git", ["rev-list", "--count", "@{upstream}..HEAD"], { cwd: repo, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim(); diff = execFileSync("git", ["diff", "--name-only", "origin/HEAD...HEAD"], { cwd: repo, encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }); } catch {} if (!remotes.trim() || !status.trim() && Number(ahead) === 0 && !diff.trim()) return null; const evidence = [[/(?:https?:\/\/\S+\/-\/merge_requests\/\d+|\bMR\s*(?:URL|链接)?\s*[:：]\s*\S+)/iu, "MR URL"], [/(?:MR\s*)?pipeline.*(?:success|通过|成功)/iu, "MR pipeline success"], [/(?:merge\s+commit|合并提交)\s*[:：]?\s*[0-9a-f]{7,40}/iu, "merge commit"], [/(?:master|main|主分支|post-merge).*(?:pipeline|CI).*(?:success|通过|成功)/iu, "master/main pipeline success"]], missing = evidence.filter(([pattern]) => !pattern.test(text)).map(([, label]) => label); return missing.length ? gate("Delivery Closure Gate", `CI-gated 仓库完成态缺少远端闭环证据：${missing.join("、")}。`, "MR、MR pipeline、merge commit 和主分支 pipeline 的真实结果。", "继续执行可逆交付步骤；仅在用户明确暂停或凭据/Runner 阻塞时降级状态并说明原因。") : null; }
function externalEffects(event, text) { if (!successful(text)) return null; const all = receipts(event), currentTurn = event?.turn_id ?? event?.turnId, scoped = currentTurn ? all.filter((item) => !item.turnId && !item.turn_id || item.turnId === currentTurn || item.turn_id === currentTurn) : all, verifies = scoped.filter((item) => receiptPassed(item) && (item.evidenceKind ?? item.evidence_kind) === "verification"), pending = scoped.filter((item) => receiptPassed(item) && (item.evidenceKind ?? item.evidence_kind) === "mutation" && (item.completionPolicy ?? item.completion_policy) === "requires-verifier").filter((mutation) => { const id = receiptInvocation(mutation), subject = mutation.completionSubjectDigest ?? mutation.completion_subject_digest, allowed = mutation.completionVerifierToolIds ?? mutation.completion_verifier_tool_ids ?? []; return id && subject && !verifies.some((verification) => (verification.verifiesInvocationId ?? verification.verifies_invocation_id) === id && allowed.includes(receiptTool(verification)) && (verification.completionSubjectDigest ?? verification.completion_subject_digest) === subject); }); return pending.length ? gate("External Effect Closure Gate", `外部 mutation 尚无匹配 verification receipt：${pending.map((item) => `${receiptTool(item)}@${receiptInvocation(item)}`).join("、")}。`, "与 mutation invocation/subject 关联的成功 verifier 收据。", "调用允许的 verification 工具并传入原 mutation invocation ID。") : null; }

export function stopViolation(event) { if (event?.stop_hook_active || event?.stopHookActive) return null; const text = finalText(event); if (!text) return null; const active = activeSkills(event); const gates = [() => nextStepGate(text), () => solvability(text), () => pptx(event, text, active), () => designEvidence(event, text, active), () => videoEvidence(event, text, active), () => provenance(event, text), () => tdd(event, text, active), () => gitlabEvidence(event, text, active), () => taskLedger(event, text, active), () => migrationLedger(event, text, active), () => delivery(event, text), () => externalEffects(event, text)]; for (const check of gates) { try { const violation = check(); if (violation) return violation; } catch {} } return null; }
