import type { DomainEngineeringPolicy } from "@harness/core/domain-engineering-hook";

export const policy: DomainEngineeringPolicy = {
 plugin:"python-engineering",
 displayName:"Python Engineering",
 protections:[
 { id:"python-lockfiles", match:/(?:^|\/)(?:pdm\.lock|Pipfile\.lock|poetry\.lock|uv\.lock)$/iu, reason:"Python lockfiles are generated by package managers.", recovery:"Change pyproject.toml or the relevant declaration and regenerate the lock." },
 { id:"python-environments", match:/(?:^|\/)(?:\.venv|venv|__pypackages__)(?:\/|$)/iu, reason:"Python environments are package-manager-owned.", recovery:"Change sources or declarations and recreate the environment." },
],
 validators:[
 { id:"pythonSyntax", kind:"python", match:/\.py$/iu, mode:"block" },
 { id:"ruff", kind:"ruff", match:/\.py$/iu, mode:"report" },
 { id:"pythonJson", kind:"json", match:/\.json$/iu, mode:"block" },
],
};
